import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { ProductWhereUniqueInput } from "../product/ProductWhereUniqueInput";
import { ClientWhereUniqueInput } from "../client/ClientWhereUniqueInput";
import { SupplierWhereUniqueInput } from "../supplier/SupplierWhereUniqueInput";
import { TransporterWhereUniqueInput } from "../transporter/TransporterWhereUniqueInput";
import { ManagerWhereUniqueInput } from "../manager/ManagerWhereUniqueInput";

export type DeliveryWhereInput = {
  id?: StringFilter;
  deliveryNumber?: StringNullableFilter;
  secured?: BooleanNullableFilter;
  status?: "Option1";
  saleVolume?: IntNullableFilter;
  salePrice?: FloatNullableFilter;
  totalAmount?: FloatNullableFilter;
  basis?: StringNullableFilter;
  purchaseRegion?: StringNullableFilter;
  purchaseVolume?: IntNullableFilter;
  deficit?: IntNullableFilter;
  averagePurchasePrice?: FloatNullableFilter;
  transportRate?: FloatNullableFilter;
  startOfShipment?: DateTimeNullableFilter;
  contractTrainDispatch?: DateTimeNullableFilter;
  vesselDispatch?: DateTimeNullableFilter;
  supplierPaymentStatus?: "Option1";
  paymentToSupplier?: FloatNullableFilter;
  invoiceDirectionDate?: DateTimeNullableFilter;
  clientAdvance?: FloatNullableFilter;
  advanceAmount?: FloatNullableFilter;
  documentDispatchDate?: DateTimeNullableFilter;
  clientPaymentStatus?: "Option1";
  clientPaymentAmount?: FloatNullableFilter;
  guSubmissionStatus?: "Option1";
  cnyExchangeRate?: FloatNullableFilter;
  exportContractNumber?: StringNullableFilter;
  deliveryOwner?: StringNullableFilter;
  actualShipped?: IntNullableFilter;
  plannedTrainDispatch?: DateTimeNullableFilter;
  actualTrainDispatch?: DateTimeNullableFilter;
  comments?: StringNullableFilter;
  finish?: BooleanNullableFilter;
  fss?: "Option1";
  st1?: "Option1";
  survey?: "Option1";
  paymentProblems?: BooleanNullableFilter;
  estimatedLogisticsRate?: FloatNullableFilter;
  hedgeStatus?: "Option1";
  product?: ProductWhereUniqueInput;
  client?: ClientWhereUniqueInput;
  supplier?: SupplierWhereUniqueInput;
  transporter?: TransporterWhereUniqueInput;
  manager?: ManagerWhereUniqueInput;
};
