import { ProductWhereUniqueInput } from "../product/ProductWhereUniqueInput";
import { ClientWhereUniqueInput } from "../client/ClientWhereUniqueInput";
import { SupplierWhereUniqueInput } from "../supplier/SupplierWhereUniqueInput";
import { TransporterWhereUniqueInput } from "../transporter/TransporterWhereUniqueInput";
import { ManagerWhereUniqueInput } from "../manager/ManagerWhereUniqueInput";

export type DeliveryCreateInput = {
  deliveryNumber?: string | null;
  secured?: boolean | null;
  status?: "Option1" | null;
  saleVolume?: number | null;
  salePrice?: number | null;
  totalAmount?: number | null;
  basis?: string | null;
  purchaseRegion?: string | null;
  purchaseVolume?: number | null;
  deficit?: number | null;
  averagePurchasePrice?: number | null;
  transportRate?: number | null;
  startOfShipment?: Date | null;
  contractTrainDispatch?: Date | null;
  vesselDispatch?: Date | null;
  supplierPaymentStatus?: "Option1" | null;
  paymentToSupplier?: number | null;
  invoiceDirectionDate?: Date | null;
  clientAdvance?: number | null;
  advanceAmount?: number | null;
  documentDispatchDate?: Date | null;
  clientPaymentStatus?: "Option1" | null;
  clientPaymentAmount?: number | null;
  guSubmissionStatus?: "Option1" | null;
  cnyExchangeRate?: number | null;
  exportContractNumber?: string | null;
  deliveryOwner?: string | null;
  actualShipped?: number | null;
  plannedTrainDispatch?: Date | null;
  actualTrainDispatch?: Date | null;
  comments?: string | null;
  finish?: boolean | null;
  fss?: "Option1" | null;
  st1?: "Option1" | null;
  survey?: "Option1" | null;
  paymentProblems?: boolean | null;
  estimatedLogisticsRate?: number | null;
  hedgeStatus?: "Option1" | null;
  product?: ProductWhereUniqueInput | null;
  client?: ClientWhereUniqueInput | null;
  supplier?: SupplierWhereUniqueInput | null;
  transporter?: TransporterWhereUniqueInput | null;
  manager?: ManagerWhereUniqueInput | null;
};
