/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ManagerService } from "../manager.service";
import { ManagerCreateInput } from "./ManagerCreateInput";
import { Manager } from "./Manager";
import { ManagerFindManyArgs } from "./ManagerFindManyArgs";
import { ManagerWhereUniqueInput } from "./ManagerWhereUniqueInput";
import { ManagerUpdateInput } from "./ManagerUpdateInput";
import { DeliveryFindManyArgs } from "../../delivery/base/DeliveryFindManyArgs";
import { Delivery } from "../../delivery/base/Delivery";
import { DeliveryWhereUniqueInput } from "../../delivery/base/DeliveryWhereUniqueInput";

export class ManagerControllerBase {
  constructor(protected readonly service: ManagerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Manager })
  async createManager(
    @common.Body() data: ManagerCreateInput
  ): Promise<Manager> {
    return await this.service.createManager({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        phone: true,
        department: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Manager] })
  @ApiNestedQuery(ManagerFindManyArgs)
  async managers(@common.Req() request: Request): Promise<Manager[]> {
    const args = plainToClass(ManagerFindManyArgs, request.query);
    return this.service.managers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        phone: true,
        department: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Manager })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async manager(
    @common.Param() params: ManagerWhereUniqueInput
  ): Promise<Manager | null> {
    const result = await this.service.manager({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        phone: true,
        department: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Manager })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateManager(
    @common.Param() params: ManagerWhereUniqueInput,
    @common.Body() data: ManagerUpdateInput
  ): Promise<Manager | null> {
    try {
      return await this.service.updateManager({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          phone: true,
          department: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Manager })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteManager(
    @common.Param() params: ManagerWhereUniqueInput
  ): Promise<Manager | null> {
    try {
      return await this.service.deleteManager({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          phone: true,
          department: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/deliveries")
  @ApiNestedQuery(DeliveryFindManyArgs)
  async findDeliveries(
    @common.Req() request: Request,
    @common.Param() params: ManagerWhereUniqueInput
  ): Promise<Delivery[]> {
    const query = plainToClass(DeliveryFindManyArgs, request.query);
    const results = await this.service.findDeliveries(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deliveryNumber: true,
        secured: true,
        status: true,
        saleVolume: true,
        salePrice: true,
        totalAmount: true,
        basis: true,
        purchaseRegion: true,
        purchaseVolume: true,
        deficit: true,
        averagePurchasePrice: true,
        transportRate: true,
        startOfShipment: true,
        contractTrainDispatch: true,
        vesselDispatch: true,
        supplierPaymentStatus: true,
        paymentToSupplier: true,
        invoiceDirectionDate: true,
        clientAdvance: true,
        advanceAmount: true,
        documentDispatchDate: true,
        clientPaymentStatus: true,
        clientPaymentAmount: true,
        guSubmissionStatus: true,
        cnyExchangeRate: true,
        exportContractNumber: true,
        deliveryOwner: true,
        actualShipped: true,
        plannedTrainDispatch: true,
        actualTrainDispatch: true,
        comments: true,
        finish: true,
        fss: true,
        st1: true,
        survey: true,
        paymentProblems: true,
        estimatedLogisticsRate: true,
        hedgeStatus: true,

        product: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        supplier: {
          select: {
            id: true,
          },
        },

        transporter: {
          select: {
            id: true,
          },
        },

        manager: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/deliveries")
  async connectDeliveries(
    @common.Param() params: ManagerWhereUniqueInput,
    @common.Body() body: DeliveryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveries: {
        connect: body,
      },
    };
    await this.service.updateManager({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/deliveries")
  async updateDeliveries(
    @common.Param() params: ManagerWhereUniqueInput,
    @common.Body() body: DeliveryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveries: {
        set: body,
      },
    };
    await this.service.updateManager({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/deliveries")
  async disconnectDeliveries(
    @common.Param() params: ManagerWhereUniqueInput,
    @common.Body() body: DeliveryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveries: {
        disconnect: body,
      },
    };
    await this.service.updateManager({
      where: params,
      data,
      select: { id: true },
    });
  }
}
