/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TransporterService } from "../transporter.service";
import { TransporterCreateInput } from "./TransporterCreateInput";
import { Transporter } from "./Transporter";
import { TransporterFindManyArgs } from "./TransporterFindManyArgs";
import { TransporterWhereUniqueInput } from "./TransporterWhereUniqueInput";
import { TransporterUpdateInput } from "./TransporterUpdateInput";
import { DeliveryFindManyArgs } from "../../delivery/base/DeliveryFindManyArgs";
import { Delivery } from "../../delivery/base/Delivery";
import { DeliveryWhereUniqueInput } from "../../delivery/base/DeliveryWhereUniqueInput";

export class TransporterControllerBase {
  constructor(protected readonly service: TransporterService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Transporter })
  async createTransporter(
    @common.Body() data: TransporterCreateInput
  ): Promise<Transporter> {
    return await this.service.createTransporter({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        phoneNumber: true,
        email: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Transporter] })
  @ApiNestedQuery(TransporterFindManyArgs)
  async transporters(@common.Req() request: Request): Promise<Transporter[]> {
    const args = plainToClass(TransporterFindManyArgs, request.query);
    return this.service.transporters({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        phoneNumber: true,
        email: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Transporter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async transporter(
    @common.Param() params: TransporterWhereUniqueInput
  ): Promise<Transporter | null> {
    const result = await this.service.transporter({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        phoneNumber: true,
        email: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Transporter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTransporter(
    @common.Param() params: TransporterWhereUniqueInput,
    @common.Body() data: TransporterUpdateInput
  ): Promise<Transporter | null> {
    try {
      return await this.service.updateTransporter({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          phoneNumber: true,
          email: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Transporter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTransporter(
    @common.Param() params: TransporterWhereUniqueInput
  ): Promise<Transporter | null> {
    try {
      return await this.service.deleteTransporter({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          phoneNumber: true,
          email: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/deliveries")
  @ApiNestedQuery(DeliveryFindManyArgs)
  async findDeliveries(
    @common.Req() request: Request,
    @common.Param() params: TransporterWhereUniqueInput
  ): Promise<Delivery[]> {
    const query = plainToClass(DeliveryFindManyArgs, request.query);
    const results = await this.service.findDeliveries(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deliveryNumber: true,
        secured: true,
        status: true,
        saleVolume: true,
        salePrice: true,
        totalAmount: true,
        basis: true,
        purchaseRegion: true,
        purchaseVolume: true,
        deficit: true,
        averagePurchasePrice: true,
        transportRate: true,
        startOfShipment: true,
        contractTrainDispatch: true,
        vesselDispatch: true,
        supplierPaymentStatus: true,
        paymentToSupplier: true,
        invoiceDirectionDate: true,
        clientAdvance: true,
        advanceAmount: true,
        documentDispatchDate: true,
        clientPaymentStatus: true,
        clientPaymentAmount: true,
        guSubmissionStatus: true,
        cnyExchangeRate: true,
        exportContractNumber: true,
        deliveryOwner: true,
        actualShipped: true,
        plannedTrainDispatch: true,
        actualTrainDispatch: true,
        comments: true,
        finish: true,
        fss: true,
        st1: true,
        survey: true,
        paymentProblems: true,
        estimatedLogisticsRate: true,
        hedgeStatus: true,

        product: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        supplier: {
          select: {
            id: true,
          },
        },

        transporter: {
          select: {
            id: true,
          },
        },

        manager: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/deliveries")
  async connectDeliveries(
    @common.Param() params: TransporterWhereUniqueInput,
    @common.Body() body: DeliveryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveries: {
        connect: body,
      },
    };
    await this.service.updateTransporter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/deliveries")
  async updateDeliveries(
    @common.Param() params: TransporterWhereUniqueInput,
    @common.Body() body: DeliveryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveries: {
        set: body,
      },
    };
    await this.service.updateTransporter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/deliveries")
  async disconnectDeliveries(
    @common.Param() params: TransporterWhereUniqueInput,
    @common.Body() body: DeliveryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveries: {
        disconnect: body,
      },
    };
    await this.service.updateTransporter({
      where: params,
      data,
      select: { id: true },
    });
  }
}
